# Тихонов Илья

# Домашнее задание 2 (10 баллов).

*Все задания ниже имеют равный вес*

Код для импорта мы написали за вас (не благодарите, нам не трудно). Дальше код будете писать вы. 

[Тут](https://habr.com/ru/companies/ruvds/articles/494720/) шпора по pandas. За основу домашнего задания взят ноутбук [отсюда](https://rutube.ru/video/f884aa6ed5f94120b7304506042fe5bb/) (не подглядывайте!).

In [187]:
import pandas as pd
import numpy as np

#### Описание данных

Автор д/з - плохой человек, который не стал переводить описание с мотивировкой, что весь DS на английском. Так что описание полей будет на английском:

1. Account ID
- Description: A unique identifier for each social media account in the dataset.
- Type: Integer
- Example: 1, 2, 3, …
2. Username
- Description: The username or handle of the social media account.
- Type: String
- Example: john_doe, tech_guru_22, fitness_freak
3. Platform
- Description: The social media platform the account is using (Instagram, Twitter, Facebook, TikTok, LinkedIn).
- Type: Categorical (String)
- Example: Instagram, Twitter, Facebook, TikTok, LinkedIn
4. Follower Count
- Description: The total number of followers the account has.
- Type: Integer
- Example: 1500, 245000, 78000
5. Posts Per Week
- Description: The average number of posts the account creates per week.
- Type: Integer
- Example: 3, 5, 7
6. Engagement Rate
- Description: The percentage of interactions (likes, comments, shares) relative to the follower count. This is a measure of how engaging the content is.
- Type: Float
- Range: 0.01 to 0.15
- Example: 0.045 (4.5% engagement rate)
7. Ad Spend (USD)
- Description: The monthly amount spent on advertising or promoting posts.
- Type: Float
- Example: 150.75, 850.00, 300.50
8. Conversion Rate
- Description: The percentage of users who take a desired action (e.g., clicking a link, signing up, etc.) after interacting with an ad.
- Type: Float
- Range: 0.01 to 0.05 (1% to 5% conversion rate)
- Example: 0.025 (2.5% conversion rate)
9. Campaign Reach
- Description: The total number of unique users reached by the user’s campaigns in a given month.
- Type: Integer
- Example: 5000, 20000, 15000

#### Задание 0

Подгрузите данные. Да-да, за чтение таблицы баллов не будет))

**Hint**: [pd.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

In [188]:
df = pd.read_csv("data.csv")
df.shape

(10000, 9)

In [189]:
df.head(5)

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302
2,3,qthomas,Facebook,218870,3,0.1020,150.36,0.0318,11043
3,4,carlosholt,Instagram,207432,6,0.0834,932.62,0.0400,12074
4,5,parsonsashley,Facebook,350204,2,0.0642,504.44,0.0463,14083

In [190]:
df.dtypes

Account ID           int64
Username            object
Platform            object
Follower Count       int64
Posts Per Week       int64
Engagement Rate    float64
Ad Spend (USD)     float64
Conversion Rate    float64
Campaign Reach       int64
dtype: object

#### Задание 1

Колонка `Platform` содержит название различных платформ. Давайте представим, что в них есть некоторое отношение порядка. Закодируйте каждую платформу целым числом (от 0 до N) и положите этот "код" в новую колонку `Platform_Code`. Теперь вычислите корреляцию Спирмена между всеми парами колонок в датасете (результатом будет таблица корреляций). В качестве ответа выведите значение корреляции `Platform_Code` с `Engagement Rate`. Можете после вывода числа еще коротко написать, что оно означает (нет, это не оценивается).

**Hint**: [pd.factorize](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.factorize.html), [pd.DataFrame.select_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html), [pd.DataFrame.corr](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html).

In [191]:
df["Platform_Code"] = pd.factorize(df["Platform"])[0]
df.head(2)

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308,0
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302,1

In [192]:
df_num = df.select_dtypes(include=[np.number])
df_num.corr("spearman").loc["Platform_Code", "Engagement Rate"]

np.float64(0.03138169529349812)

#### Задание 2

Теперь посмотрите на столбец `Follower Count`. В нем какие-то числа. Иногда бывает полезно провести дискретизацию такого признака. Разбейте все значения в столбце на 4 группы: "Low", "Medium", "High", "Very High". Каждая группа включает в себя новые 25% данных. То есть, Low включает в себя 25% самых маленьких значений признака и так далее. Положите значения "Low", "Medium", "High" или "Very High" для каждого сэмпла датасета в новую колонку `Follower_Bin`. Теперь посчитайте среднее значение `Engagement Rate` для каждой категории из `Follower_Bin`. В качестве ответа выведите значение для категории "High".

**Hint**: [pd.qcut](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.qcut.html), [pd.groupby](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html), [pd.DataFrame.mean](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)

In [193]:
df["Follower_Bin"] = pd.qcut(df["Follower Count"], q=4, labels=["Low", "Medium", "High", "Very High"])
df.head(5)

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code,Follower_Bin
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308,0,Low
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302,1,Very High
2,3,qthomas,Facebook,218870,3,0.1020,150.36,0.0318,11043,2,Low
3,4,carlosholt,Instagram,207432,6,0.0834,932.62,0.0400,12074,3,Low
4,5,parsonsashley,Facebook,350204,2,0.0642,504.44,0.0463,14083,2,Medium

In [194]:
df.groupby("Follower_Bin", observed=False)["Engagement Rate"].mean().loc["High"]

np.float64(0.08655032)

#### Задание 3

Иногда бывает полезно превратить широкую таблицу в длинную (например, для визуализаций сразу нескольких признаков на одной картинке). Да, звучит странно, но именно этим вы сейчас и займетесь. Сделайте новый датафрейм `melted_df`, в который вы поместите каждый сэмпл датасета 6 раз: по одному разу на значение из 'Follower Count', 'Posts Per Week', 'Ad Spend (USD)', 'Conversion Rate', 'Engagement Rate' и 'Campaign Reach'. То есть, вы берете сэмпл из датасета (строку) и превращаете ее в 6 отдельных строк. Каждая отдельная строка в столбце `Metric` имеет имя из предложенного списка 5 признаков, а в столбце `Value` - значение данного сэмпла по этому признаку. Значение `Platform` повторяется в этих 6 строках.

Иначе говоря, 

```json
{
    "Account ID": 1,
    "Username": "harrislisa",
    "Platform": "TikTok",
    "Follower Count": 54217,
    "Posts Per Week": 3,
    "Engagement Rate": 0.0986,
    "Ad Spend (USD)": 538.1,
    "Conversion Rate": 0.049,
    "Campaign Reach": 1308,
    "Platform_Code": 0,
    "Follower_Bin": "Low"
}
```

превращается в 

```json
{
    "Platform": "TikTok",
    "Metric": "Follower Count",
    "Value": 54217,
},
{
    "Platform": "TikTok",
    "Metric": "Posts Per Week",
    "Value": 3,
}, ...
```

Для каждого уникальной пары значений (`Platform`, `Metric`) посчитайте моду среди всех значений `Value` для этой пары, результат сделайте списком и оставьте только наибольшее. В качестве ответа выведите сумму полученных мод (сумму всех значений в столбце `Value` уже после вычисления мод). Иначе говоря, выведите сумму всех мод значений для всех уникальных пар (`Platform`, `Metric`).

**Hint**: [pd.melt](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.melt.html), [pd.DataFrame.mode](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mode.html), [pd.DataFrameGroupBy.agg](https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.DataFrameGroupBy.agg.html)

In [195]:
# (づ๑•ᴗ•๑)づ♡
df_melt = pd.melt(df, id_vars=['Platform'], value_vars=['Follower Count', 'Posts Per Week', 'Ad Spend (USD)', 'Conversion Rate', 'Engagement Rate', 'Campaign Reach'], value_name="Value", var_name="Metric")
df_melt.sample(5)

       Platform           Metric        Value
16843  LinkedIn   Posts Per Week       4.0000
31773    TikTok  Conversion Rate       0.0128
5729   Facebook   Follower Count  572392.0000
50748   Twitter   Campaign Reach    2193.0000
35187  Facebook  Conversion Rate       0.0237

In [196]:
df_melt.groupby(["Platform", "Metric"], observed=False)["Value"].agg(lambda x: x.mode().max()).sum()

np.float64(3100285.4716)

#### Задание 4

А теперь хочется посмотреть на самые популярные аккаунты на разных платформах. Для каждой платформы отсортируйте датафрейм по убыванию количества подписчиков (`Follower Count`) - да, без циклов, сразу для всех платформ сделать сортировку, а затем оставьте только первые три записи для каждой платформы - это и будут три самых популярных аккаунта для каждой платформы. В качестве ответа выведите саму таблицу и минимальное значение `Follower Count` в ней.

**Hint**: к *groupby* можно применять функции - это эквивалентно применению функции к каждой "группе" внутри groupby-объекта. Читайте [про применение apply к датафрейму после groupby](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#flexible-apply).

In [197]:
# ε(´סּ︵סּ`)з
df_platforms = df.groupby("Platform").apply(lambda x: x.sort_values("Follower Count", ascending=False).head(3), include_groups=False)
df_platforms

                Account ID         Username  Follower Count  Posts Per Week  \
Platform
Facebook  2403        2404           eric65          999982               6
          7350        7351     patricknoble          997915               3
          1689        1690      chavezjason          997512               7
Instagram 8685        8686  alexandersamuel          999726               3
          3965        3966         lrodgers          999351               1
          2189        2190           jbrown          997844               5
LinkedIn  3039        3040          toneill          999055               4
          6359        6360    andrewgregory          998968               7
          2159        2160     ashleycooper          998925               6
TikTok    5838        5839     edwardthomas          999739               7
          4234        4235    andradewesley          999234               5
          2575        2576     williamwyatt          998623               6
Twitter   4920        4921      teresaellis          999919               6
          9684        9685           sriley          999442               3
          7576        7577       peggymunoz          998216               6

                Engagement Rate  Ad Spend (USD)  Conversion Rate  \
Platform
Facebook  2403           0.0642          884.06           0.0281
          7350           0.0834          429.01           0.0182
          1689           0.0834          993.20           0.0397
Instagram 8685           0.0834          687.61           0.0205
          3965           0.0834          565.07           0.0335
          2189           0.0642          505.61           0.0202
LinkedIn  3039           0.0642          799.49           0.0174
          6359           0.1020          797.64           0.0351
          2159           0.0856          474.46           0.0156
TikTok    5838           0.0642          630.77           0.0325
          4234           0.0834          872.77           0.0481
          2575           0.0856          477.98           0.0250
Twitter   4920           0.0834          411.63           0.0460
          9684           0.0834          206.84           0.0225
          7576           0.0642          456.61           0.0456

                Campaign Reach  Platform_Code Follower_Bin
Platform
Facebook  2403           17312              2    Very High
          7350           25985              2    Very High
          1689           45717              2    Very High
Instagram 8685           11050              3    Very High
          3965           12391              3    Very High
          2189           14717              3    Very High
LinkedIn  3039           21862              1    Very High
          6359           15552              1    Very High
          2159           45956              1    Very High
TikTok    5838           35523              0    Very High
          4234           17188              0    Very High
          2575           43299              0    Very High
Twitter   4920            3975              4    Very High
          9684           12783              4    Very High
          7576           22037              4    Very High

In [198]:
df_platforms["Follower Count"].min()

np.int64(997512)

#### Задание 5

Хочется посчитать какую-то метрику. Мы хотим посмотреть, на отношение разности суммы подписчиков аккаунтов с высокой и низкой конверсией к суммарному охвату рекламы на каждой платформе. То есть, мы делим аккаунты на две группы: высокая и низка конверсия. Затем мы смотрим на то, на сколько сильно влияние аккаунтов с высокой конверсией по сравнению с аккаунтами с низкой конверсией. 

Давайте определим *Conversion Influence* следущим образом:

$$Conversion Influence = \frac{Total Follower\ Count (High) - Total Follower\ Count (Low)}{Total Campaign Reach (High)+Total Campaign Reach (Low)}$$

Считать эту метрику мы будет для каждой `Platform`. В этой формуле High - это значения всех сэмплов датасета, в которых `Conversion Rate` больше медианы, а `Low` - не более медианы. `Total Feature` - это суммарное количество значений `Feature` либо по `High` сэмплам, либо по `Low`.

Чтобы постоянно не пересчитывать, где High. где Low, сделайте новую колонку в датасете `Conversion_Category`. Положите в нее для каждой строки либо High, либо Low.

Выведите платформу с самым большим `Conversion Influence`.

**Hint**: данное задание не про *groupby*, а скорее про [pd.pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html). Сделайте сводную таблицу, по которой уже можно посчитать суммы, а затем подставить их в формулы.

In [199]:
# (︶ω︶)
df["Conversion_Category"] = pd.qcut(df["Conversion Rate"], q=2, labels=["Low", "High"])
df.head(5)

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code,Follower_Bin,Conversion_Category
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308,0,Low,High
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302,1,Very High,Low
2,3,qthomas,Facebook,218870,3,0.1020,150.36,0.0318,11043,2,Low,High
3,4,carlosholt,Instagram,207432,6,0.0834,932.62,0.0400,12074,3,Low,High
4,5,parsonsashley,Facebook,350204,2,0.0642,504.44,0.0463,14083,2,Medium,High

In [200]:
df_pivot = pd.pivot_table(df, index="Platform", values=["Follower Count", "Campaign Reach"], columns="Conversion_Category", aggfunc="sum", observed=False)
df_pivot

                    Campaign Reach           Follower Count
Conversion_Category            Low      High            Low       High
Platform
Facebook                  25635749  26096572      499712373  512439819
Instagram                 26482804  24250993      524726855  487970573
LinkedIn                  25147594  25186827      499766430  509450797
TikTok                    25091283  24253556      491110679  495899696
Twitter                   24566705  26376400      481382949  536955379

In [201]:
df_pivot["Conversion Influence"] = (df_pivot[("Follower Count", "High")] - df_pivot[("Follower Count", "Low")]) / (df_pivot[("Campaign Reach", "High")] + df_pivot[("Campaign Reach", "Low")])
df_pivot

                    Campaign Reach           Follower Count             \
Conversion_Category            Low      High            Low       High
Platform
Facebook                  25635749  26096572      499712373  512439819
Instagram                 26482804  24250993      524726855  487970573
LinkedIn                  25147594  25186827      499766430  509450797
TikTok                    25091283  24253556      491110679  495899696
Twitter                   24566705  26376400      481382949  536955379

                    Conversion Influence
Conversion_Category
Platform
Facebook                        0.246025
Instagram                      -0.724493
LinkedIn                        0.192400
TikTok                          0.097052
Twitter                         1.090872

In [202]:
df_pivot.nlargest(1, "Conversion Influence")

                    Campaign Reach           Follower Count             \
Conversion_Category            Low      High            Low       High
Platform
Twitter                   24566705  26376400      481382949  536955379

                    Conversion Influence
Conversion_Category
Platform
Twitter                         1.090872

#### Задание 6

Мы знаем, что вам понравилось считать метрики по формуле. Давайте закрепим этот успех. Теперь для каждой платформы посчитаем, на сколько эффективна реклама в разрезе трех последовательных записей в датасете. 

Для каждой платформы отсортируйте записи в порядке убывания `Posts Per Week`. Будто бы аккаунты, которые постят чаще, используют более "активные" стратегии по рекламе. Теперь посчитайте *скользущие суммы с окном 3* по `Campaign Reach` и `Ad Spend (USD)`. Скользящая сумма с окном N - это вы идете по массиву, берете все последовательные тройки записей и суммируете их. Для первых двух записей троек не найдется. Для них скользящее среднее - NaN, что нам не помешает. 

Теперь для каждого окна посчитайте 

$$Rolling Efficiency Ratio = \frac{Rolling Sum of Campaign Reach}{Rolling Sum of Ad Spend}$$

По сути, для каждого окна вы посчитаете сколько пользователе привлеклось за один доллар, потреченный на рекламу, в данном окне. Понятно, что значений будет столько, сколько окон. Нам интересно максимально значение такой эффективности для каждой платформы.

В качестве ответа выведите название платформы с наибольшей максимальной эффективность и наименьшей (два названия, не одно, не три, ровно два).

**Hint**: окна можно делать через [pd.DataFrame.rolling](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html).

In [203]:
# (◔/‿\◔)
df_platforms = df.groupby("Platform").apply(lambda x: x.sort_values("Posts Per Week", ascending=False), include_groups=False)
df_rolling = df_platforms[["Campaign Reach", "Ad Spend (USD)"]].apply(lambda x: x.rolling(window=3).sum())
df_rolling

               Campaign Reach  Ad Spend (USD)
Platform
Facebook 1747             NaN             NaN
         1173             NaN             NaN
         1171         39907.0         1877.13
         8191         31076.0         2564.36
         5875         42958.0         2150.35
...                       ...             ...
Twitter  5568         87896.0         2423.44
         5542        108557.0         1944.57
         5523        137495.0         1165.99
         5968        129443.0          838.55
         4860        128491.0         1561.07

[10000 rows x 2 columns]

In [204]:
df_rolling["Rolling_Efficiency_Ratio"] = df_rolling["Campaign Reach"] / df_rolling["Ad Spend (USD)"]
df_rolling

               Campaign Reach  Ad Spend (USD)  Rolling_Efficiency_Ratio
Platform
Facebook 1747             NaN             NaN                       NaN
         1173             NaN             NaN                       NaN
         1171         39907.0         1877.13                 21.259582
         8191         31076.0         2564.36                 12.118423
         5875         42958.0         2150.35                 19.977213
...                       ...             ...                       ...
Twitter  5568         87896.0         2423.44                 36.269105
         5542        108557.0         1944.57                 55.825710
         5523        137495.0         1165.99                117.921251
         5968        129443.0          838.55                154.365273
         4860        128491.0         1561.07                 82.309570

[10000 rows x 3 columns]

In [205]:
df_rolling.nlargest(1, "Rolling_Efficiency_Ratio")

                Campaign Reach  Ad Spend (USD)  Rolling_Efficiency_Ratio
Platform
Instagram 3930        136956.0          240.94                568.423674

In [206]:
df_rolling.nsmallest(1, "Rolling_Efficiency_Ratio")

               Campaign Reach  Ad Spend (USD)  Rolling_Efficiency_Ratio
Platform
Facebook 8606          9659.0         2722.05                  3.548429

#### Задание 7

Это еще не все прекрасные функции pandas, которые мы хотим вам показать. Теперь вы посчитаете, сколько аккаунтов на каждой платформе одновременно лучшие по `Engagement Rate` и `Conversion Rate`.

Сделайте два отдельных суб-сета. В одном оставьте для каждой платфмормы один топовый аккаунт по `Engagement Rate`, в другом - по `Conversion Rate`. Соедините эти два подмножества по столбцу `Platform` так, что в одно строке есть описание сразу двух аккаунтов-лидеров. Теперь посмотрите равны ли имена аккаунтов в одной строке. Выведите количество строк, в которых названия аккаунтов совпадают.

In [207]:
# ( ͡° ͜ʖ ͡°)
df_engagement = df.groupby("Platform")[["Account ID", "Username", "Engagement Rate"]].apply(lambda x: x.nlargest(1, "Engagement Rate"), include_groups=False)
df_engagement

              Account ID       Username  Engagement Rate
Platform
Facebook  2            3        qthomas            0.102
Instagram 59          60   jaimeedwards            0.102
LinkedIn  72          73        allen72            0.102
TikTok    22          23     carlosholt            0.102
Twitter   94          95  marquezedward            0.102

In [208]:
df_conversion = df.groupby("Platform")[["Account ID", "Username", "Conversion Rate"]].apply(lambda x: x.nlargest(1, "Conversion Rate"), include_groups=False)
df_conversion

                Account ID       Username  Conversion Rate
Platform
Facebook  3464        3465      michael55             0.05
Instagram 2863        2864  aprilwilliams             0.05
LinkedIn  8016        8017         jeff87             0.05
TikTok    284          285   robertmorris             0.05
Twitter   5992        5993      trobinson             0.05

In [209]:
df_merged = pd.merge(df_engagement, df_conversion, on="Platform", how="left")
df_merged

,Account ID_x,Username_x,Engagement Rate,Account ID_y,Username_y,Conversion Rate
Platform,,,,,,
Facebook,3,qthomas,0.102,3465,michael55,0.05
Instagram,60,jaimeedwards,0.102,2864,aprilwilliams,0.05
LinkedIn,73,allen72,0.102,8017,jeff87,0.05
TikTok,23,carlosholt,0.102,285,robertmorris,0.05
Twitter,95,marquezedward,0.102,5993,trobinson,0.05

In [215]:
(df_merged["Username_x"] == df_merged["Username_y"]).sum()

np.int64(0)

#### Задание 8

Давайте теперь что-то попроще сделаем. Например, посчитаем отношение суммарного количества подписчиков на аккаунтах с высокой конверсией к такой же сумме в аккаунтах с низкой конверсией (очевидно, для каждой платформы). По сути, мы просто хотим получить число, которое характеризует, на сколько сильно аккаунты с высокой конверсией "доминируют" над аккаунтами с низкой конверсией в плане количества подписчиков.

Высокой конверсией будем считать конверсию больше средней. Остальное - низкая. Посчитайте суммы подписчиков для каждой платформы, поделите одно на другое и выведите разницу между самым большим значением и самым маленьким, а также платформы, которые соотвутствуют этим значениям.

Используйте магическую команду `%%time`, чтобы замерить, сколько времени ушло на исполнение вашего pandas-скрипта.

In [211]:
df.head(2)

,Account ID,Username,Platform,Follower Count,Posts Per Week,Engagement Rate,Ad Spend (USD),Conversion Rate,Campaign Reach,Platform_Code,Follower_Bin,Conversion_Category
0,1,harrislisa,TikTok,54217,3,0.0986,538.10,0.0490,1308,0,Low,High
1,2,rhicks,LinkedIn,987518,5,0.0834,479.24,0.0174,13302,1,Very High,Low

In [219]:
df["Conversion_Category"] = np.where(df["Conversion Rate"] > df["Conversion Rate"].mean(), "High", "Low")

In [220]:
# (◡‿◡✿)
# %%time в PyCharm не работает :(
import time

t0 = time.perf_counter()


df_platforms = df.pivot_table(index="Platform", values="Follower Count", columns="Conversion_Category", aggfunc="sum", observed=False)
# print(df_platforms.to_string())
# print()

df_platforms["Ratio"] = df_platforms["High"] / df_platforms["Low"]
# print(df_platforms.to_string())
# print()

max_ratio = df_platforms.nlargest(1, "Ratio")
min_ratio = df_platforms.nsmallest(1, "Ratio")
print("DIFF =", max_ratio["Ratio"].values[0] - min_ratio["Ratio"].values[0])
print()
print(max_ratio.to_string())
print()
print(min_ratio.to_string())

t1 = time.perf_counter()
print(f"Time taken: {t1 - t0:.4f} seconds")

DIFF = 0.17688741338715763

Conversion_Category       High        Low     Ratio
Platform
Twitter              518386631  499951697  1.036873

Conversion_Category       High        Low     Ratio
Platform
Instagram            468232352  544465076  0.859986
Time taken: 0.0093 seconds

#### Задание 9

А теперь решите задание 8 чисто питоном. Никаких функций и методов pandas. Только питоновские циклы. Замерьте время выполнения кода. Наконец, сравните время в задании 8 и 9. Напишите ниже, кто же победил: чистый python и pandas?

**Hint**: Чтобы итерироваться по датафрейму, можно из него сделать генератор через [pd.DataFrame.iterrows](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html) или [pd.DataFrame.itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html#pandas.DataFrame.itertuples). К слову, это не все способы итерироваться по датафрейму.

In [218]:
# (✿◠‿◠)
t0 = time.perf_counter()

sums = {}

for platform, cat, followers in df[["Platform", "Conversion_Category", "Follower Count"]].itertuples(index=False, name=None):
    if platform not in sums:
        sums[platform] = {"High": 0.0, "Low": 0.0}
    sums[platform][cat] += float(followers)

ratios = {}
max_plat = None
min_plat = None
max_ratio = float("-inf")
min_ratio = float("inf")

for platform, d in sums.items():
    ratio = d["High"] / d["Low"]
    ratios[platform] = ratio

    if ratio > max_ratio:
        max_ratio = ratio
        max_plat = platform
    if ratio < min_ratio:
        min_ratio = ratio
        min_plat = platform


diff = max_ratio - min_ratio
print("DIFF =", diff)
print()
print("MAX:", max_plat, "Ratio =", max_ratio)
print("MIN:", min_plat, "Ratio =", min_ratio)

t1 = time.perf_counter()
print(f"\nTime taken: {t1 - t0:.4f} seconds")

DIFF = 0.17688741338715763

MAX: Twitter Ratio = 1.0368734301945974
MIN: Instagram Ratio = 0.8599860168074398

Time taken: 0.0079 seconds

**А победителем является**: удивительно но чистый питон, наверное датасет маленький

#### Задание 10

Крайне серьезное задание. Отнеситесь к нему соответствующе. В ячейке ниже напишите ваш любимый анекдот или мем (только без баянов, окей?). Можно плохие. Помните, это задание на полный балл. Проверяющий работу ассистент должен улыбнуться.

Если вставляете картинку, то убедитесь, что вы ее не подгружаете локально. А то будет неудобно - потерять балл на этом задании, когда надо было выложить картинку на облако и прокинуть ссылку. И нет, нельзя сюда просто ссылку вставить. Либо ищите, как вставить картинку, либо смешной анекдот. Есть всего два стула - выбирайте...

In [214]:
# ‿( ́ ̵ _-`)‿
# Стоят пассажиры в аэропорту, посадочный досмотр проходят. Дошла очередь до мужика с чемоданом.
# — Пожалуйста, приготовьте чемодан к осмотру.
# — Не могу.
# — Почему?
# — А у меня там бипки!
# — А что это?
# — Ну, отсосёте — покажу!
# Служба безопасности шутку не поняла, вызвала наряд полиции:
# — Гражданин, открывайте чемодан.
# — Но я не могу!
# — Почему не можете?
# — Потому что у меня там бипки!
# — «Бипки»? Что это?
# — Так отсосите мне, и я покажу!
# Отобрали чемодан, а открыть никто не может. Повезли мужика в СИЗО. В камере сидельцы расспрашивают:
# — Братуха, за что тебя?
# — Да чемодан отказался открывать.
# — А что там?
# — Да бипки там.
# — Какие нахуй «бипки»?
# — Ну отсосите мне, тогда и расскажу.
# И вот угодил мужик в лазарет, с побоями да синяками по всему телу, весь перебинтован, еле дышит. Следователи вызвали группу специалистов для вскрытия чемодана. Час, два, три пыхтели. Кое-как разворотили, смотрят — а там бипки.